### ISSUE TITLE
Support for npm or bower

### ISSUE THREAD

**Issue by jeanlauliac** [zuudo/helios.js#2]
Hi there!!

I see no `package.json` or `bower.json` in helios.js. Do you plan on supporting out-of-the-box Node.js (via npm) at some point? I'm indeed looking for a light server-side in-memory graph db, but server-side (for developing a command-line tool, not an app). I could probably use an infrastructure like Neo4j, but that's heavier.

**Comment by rootsical** [comment]
+1 for npm!
