### ISSUE TITLE
Cannot read property 'invoke' of undefined

### ISSUE THREAD

**Issue by kevinisaac** [zuudo/helios.js#5]
```
TypeError: Cannot read property 'invoke' of undefined
at GraphDatabase.loadGraphSON (/home/kevin/Code/js/node/songbase/node_modules/heliosdb/helios.js:119:27)
.......
```

The JSON file is present and it has data. Any idea why?

**Comment by fattenap** [comment]
Hi @kevinisaac,

Are you able to provide an example of the JSON file you are loading?

Thanks
Frank

**Comment by kevinisaac** [comment]
It's the default JSON file the module came with :

    {
      "graph": {
        "mode":"NORMAL",
        "vertices":[
          {"name":"marko","age":29,"_id":1,"_type":"vertex"},
          {"name":"vadas","age":27,"_id":2,"_type":"vertex"},
          {"name":"lop","lang":"java","_id":3,"_type":"vertex"},
          {"name":"josh","age":32,"_id":4,"_type":"vertex"},
          {"name":"ripple","lang":"java","_id":5,"_type":"vertex"},
          {"name":"peter","age":35,"_id":6,"_type":"vertex"}
        ],
        "edges":[
          {"weight":0.5,"_id":7,"_type":"edge","_outV":1,"_inV":2,"_label":"knows"},
          {"weight":1.0,"_id":8,"_type":"edge","_outV":1,"_inV":4,"_label":"knows"},
          {"weight":0.4,"_id":9,"_type":"edge","_outV":1,"_inV":3,"_label":"created"},
          {"weight":1.0,"_id":10,"_type":"edge","_outV":4,"_inV":5,"_label":"created"},
          {"weight":0.4,"_id":11,"_type":"edge","_outV":4,"_inV":3,"_label":"created"},
          {"weight":0.2,"_id":12,"_type":"edge","_outV":6,"_inV":3,"_label":"created"}
        ]
      }
    }

**Comment by fattenap** [comment]
Hmm, that's weird because it works for me.

How have you set up your environment. i.e. the location of files and what not.
